title: Book Light Editorial
author:
  name: Nick Hayward
  email: 'nhayward2011@gmail.com'
metadata:
  description: 'Book Light Editorial offers freelance developmental and copy editing services and writing tips for indie authors and publishing authors'
  author: 'Carly Bornstein-Hayward'
